calvinandhobbes/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('allbooks/', views.allbooks, name='books'),
    path('details/<int:book_id>/', views.detailbooks, name='details'),
    path('books/create/', views.BookCreate.as_view(), name='books_create'),
    path('books/<int:pk>/update/', views.BookUpdate.as_view(), name='books_update'),
    path('books/<int:pk>/delete/', views.BookDelete.as_view(), name='books_delete'),
    path('books/<int:pk>/addsales/', views.add_sales, name="add_sales"),
    path('store/create', views.StoreCreate.as_view(), name="store_create"),
    path('store/<int:pk>/update/', views.StoreUpdate.as_view(), name='store_update'),
    path('store/', views.StoreList.as_view(), name="store_list"),
    path('store/<int:pk>/', views.StoreDetail.as_view(), name="store_details"),
    path('store/<int:pk>/delete/', views.StoreDelete.as_view(), name="store_delete")
]

main_app/models.py
from django.db import models
from django.urls import reverse

# Create your models here.

class Store(models.Model):
    name = models.CharField(max_length=50)
    location = models.CharField(max_length=50)

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('store_details', kwargs={'pk': self.id})
    
class Book(models.Model):
    title = models.CharField(max_length=100)
    date = models.CharField(max_length=15)
    isbn = models.CharField(max_length=20)
    details = models.TextField(max_length=250)
    store = models.ManyToManyField(Store)
    def __str__(self):
        return f'{self.title} ({self.id})'
    
    def get_absolute_url(self):
        return reverse('details', kwargs={'book_id': self.id})
    
class Sales(models.Model):
    date = models.DateField()
    price = models.CharField(max_length=5)
    book = models.ForeignKey(Book, on_delete=models.CASCADE, default=1)

    def __str__(self):
        return f"{self.book.title} on {self.date}"
    

main_app/forms.py
from django.forms import ModelForm
from .models import Sales

class SalesForm(ModelForm):
    class Meta:
        model = Sales
        fields = ['date', 'price']

calvinandhobbes/views.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about', views.about, name='about'),
    path('cats/', views.cats_index, name='index'),
]

main_app/views.py
from django.shortcuts import render, redirect
from .models import Book, Store
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from .forms import SalesForm

#The data for my list of objects I just used from wikipedia

calvinandhobbes = [
    {'title': 'Calvin and Hobbes', 'date': 'April 1987', 'isbn': 'ISBN 0-8362-2088-9', 'details': 'Foreword by Garry Trudeau; original black-and-white artwork scattered throughout book'},
    {'title': 'Something Under the Bed is Drooling', 'date': 'April 1988', 'isbn': 'ISBN 0-8362-1825-6', 'details': 'Foreword by Pat Oliphant; original black-and-white artwork scattered throughout book'},
    {'title': 'The Essential Calvin and Hobbes: A Calvin and Hobbes Treasury', 'date': 'September 1988', 'isbn': 'ISBN 0-8362-1805-1', 'details': 'Foreword by Charles M. Schulz; an illustrated poem, "A Nauseous Nocturne"'},
    {'title': 'Yukon Ho!', 'date': 'March 1989', 'isbn': 'ISBN 0-8362-1835-3', 'details': 'The "Yukon Song"; original black-and-white artwork scattered throughout book'},
    {'title': 'The Calvin and Hobbes Lazy Sunday Book: A Collection of Sunday Calvin and Hobbes Cartoons', 'date': 'September 1989', 'isbn': 'ISBN 0-8362-1852-3', 'Details': 'Ten-page story "Spaceman Spiff: Interplanetary Explorer Extraordinaire!"; afterword by Bill Watterson; and a specially redrawn version of the August 28, 1988 strip'},
    {'title': 'Weirdos from Another Planet!', 'date': 'March 1990', 'isbn': 'ISBN 0-8362-1862-0', 'details': 'Original black-and-white artwork scattered throughout book'},
    {'title': 'The Authoritative Calvin and Hobbes: A Calvin and Hobbes Treasure', 'date': 'October 1990', 'isbn': 'ISBN 0-8362-1822-1', 'details': 'Seven-page story in which Calvin becomes an elephant'},
    {'title': 'The Revenge of the Baby-Sat', 'date': 'April 1991', 'isbn': 'ISBN 0-8362-1866-3', 'details': ''},
    {'title': 'Scientific Progress Goes \"Boink\"', 'date': 'October 1991', 'isbn': 'ISBN 0-8362-1878-7', 'details': ''},
    {'title': 'Attack of the Deranged Mutant Killer Monster Snow Goons', 'date': 'April 1992', 'isbn': 'ISBN 0-8362-1883-3', 'details': ''},
    {'title': 'The Indispensable Calvin and Hobbes: A Calvin and Hobbes Treasury', 'date': 'October 1992', 'isbn': 'ISBN 0-8362-1898-1', 'details': 'Several illustrated poems'},
    {'title': 'Teaching with Calvin and Hobbes', 'date': '1993', 'isbn': 'ISBN 1-8788-4915-8', 'details': 'Lesson units by Linda Holmen and Mary Santella-Johnson based on the strips'},
    {'title': 'The Days Are Just Packed', 'date': 'October 1993', 'isbn': 'ISBN 0-8362-1735-7', 'details': ''},
    {'title': 'Homicidal Psycho Jungle Cat', 'date': 'October 1994', 'isbn': 'ISBN 0-8362-1769-1', 'details': ''},
    {'title': 'The Calvin and Hobbes Tenth Anniversary Book', 'date': 'October 1995', 'isbn': 'ISBN 0-8362-0438-7', 'details': 'Commentary by Watterson and annotations on individual strips'},
    {'title': 'There\'s Treasure Everywhere', 'date': 'March 1996', 'isbn': 'ISBN 0-8362-1312-2', 'details': ''},
    {'title': 'It\'s a Magical World', 'date': 'October 1996', 'isbn': 'ISBN 0-8362-2136-2', 'details': ''},
    {'title': 'Calvin and Hobbes: Sunday Pages, 1985-1995: An Exhibition Catalogue', 'date': 'September 2001', 'isbn': 'ISBN 0-7407-2135-6', 'details': 'Original sketches and commentary by Watterson'},
    {'title': 'The Complete Calvin and Hobbes (hardcover)', 'date': 'October 2005', 'isbn': 'ISBN 0-7407-4847-5', 'details': 'Introduction and commentary'},
    {'title': 'The Complete Calvin and Hobbes (paperback)', 'date': 'November 2012', 'isbn': 'ISBN 1-4494-3325-1', 'details': 'Introduction and commentary'},
    {'title': 'Exploring Calvin and Hobbes: An Exhibition Catalogue', 'date': 'February 2015', 'isbn': 'ISBN 978-1-4494-6036-5', 'details': 'Original art and commentary by Watterson'}
]
# Create your views here.

def index(request):
    books = Book.objects.all()
    return render(request, 'index.html')

def about(request):
    books = Book.objects.all()
    return render(request, 'books/about.html', {'candh': books})

def allbooks(request):
    books = Book.objects.all()
    return render(request, 'books/index.html', {'candh': books})

def detailbooks(request, book_id):
    books = Book.objects.get(id=book_id)
    sales_form = SalesForm()
    stores = books.store.all().values_list('id')
    books_not_in_stores = Store.objects.exclude(id__in=stores)
    return render(request, 'books/detail.html', {
        'candh': books,
        'sales_form': sales_form,
        'stores': stores,
        'not_in_store': books_not_in_stores
    })

def add_sales(request, pk):
    form = SalesForm(request.POST)
    if form.is_valid():
        new_sale = form.save(commit=False)
        new_sale.book_id = pk
        new_sale.save()
    return redirect('details', pk)

class BookCreate(CreateView):
    model = Book
    fields = '__all__'

class BookUpdate(UpdateView):
    model = Book
    fields = ['date', 'isbn', 'details']

class BookDelete(DeleteView):
    model = Book
    success_url = '/allbooks/'

class StoreCreate(CreateView):
    model = Store
    fields = '__all__'

class StoreUpdate(UpdateView):
    model = Store
    fields = ['name', 'location']

class StoreList(ListView):
    model = Store

class StoreDetail(DetailView):
    model = Store

class StoreDelete(DeleteView):
    model = Store
    success_url='/store'

main_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/style.css' %}" >
    <title>Document</title>
</head>
<body>
    <nav>
        <div class="nav"></div>
        <div class="nav">
            <a href="{% url 'about' %}"><h3>About</h3></a>
        </div>
        <div class="nav">
            <a href="{% url 'books' %}"><h3>All Books</h3></a>
        </div>
        <div class="nav">
            <a href="{% url 'books_create' %}"><h3>Create Book</h3></a>
        </div>
        <div class="nav"><a href="{% url 'store_create' %}"><h3>Add Store</h3></a></div>
        <div class="nav"><a href="{% url 'store_list' %}">View All Stores</a></div>
    </nav>
    <main>
        {% block content %}
        {% endblock %}
    </main>
    
</body>
</html>

main_app/templates/books/about.html
{% extends '../base.html' %}

{% block content %}
{% for book in candh %}
    <div class="aboutb">
        <div class="b">
            <h2>{{book.title}}:<h2>
        </div>
        <div class="b">
            <h3>{{book.details}}</h3>
        </div>
    </div>    
{% endfor %}
{% endblock %}

main_app/templates/books/detail.html
{% extends '../base.html' %}
{% block content %}
    <div class="container">
        <div></div>
        <div class = "card">
            <div>{{candh.title}}</div>
            <div>{{candh.date}}</div>
            <div>{{candh.isbn}}</div>
            <div>{{candh.details}}</div>
            <div><a href="{% url 'books_update' candh.id %}">Edit</a></div>
            <div><a href="{% url 'books_delete' candh.id %}">Delete</a></div>
        </div>
        <form action="{% url 'add_sales' candh.id %}" method="POST">
            {% csrf_token %}
            <!-- Render the inputs -->
            {{ sales_form.as_p }}
            <input type="submit" class="btn" value="Add Sale">
          </form>
        <div></div>
    </div>
    <table>
        <tr>
            <td>
                Sales
            </td>
        </tr>
    {% for sale in candh.sales_set.all %}
    <tr>
      <td>{{sale.date}}</td>
      <td>{{sale.get_price_display}}</td>
    </tr>
    {% endfor %}
    </table>
    <h3>Where books can be found</h3>
    {% if stores.count %}
    {% for store in stores %}
    <div class="card">Stores book can be found in {{store.name}}, {{store.location}} </div>
    {% endfor %}
    {% endif %}

    <h3>Stores books could be added to</h3>
    {% if not_in_store.count %}
    {% for store in not_in_store.all %}
        <div class="card">
            <div>Stores book could be available in {{store.name}}, {{store.location}}</div>
        </div>
    {% endfor %}
    {% endif %}
    

{% endblock %}

<script>
    const dateEl = document.getElementById('id_date')
    M.Datepicker.init(dateEl, {
      format: 'yyyy-mm-dd',
      defaultDate: new Date(),
      setDefaultDate: true,
      autoClose: true
    })
    const selectEl = document.getElementById('id_meal');
    M.FormSelect.init(selectEl)
  </script>

main_app/templates/books/index.html
{% extends '../base.html' %}

{% block content %}
        <div id="red"></div>
            {% for book in candh %}
                <a href="{% url 'details' book.id %}">
                <div class="card">
                    <div>{{book.title}}</div>
                    <div>{{book.date}}</div>
                    <div>{{book.isbn}}</div>
                    <div>{{book.details}}</div>
            </div>
                </a>
            {% endfor %}
        <div id="blue"></div>
{% endblock %}

main_app/templates/index.html
{% extends 'base.html' %}

{% block content %}

<h1>Home</h1>

{% endblock %}

main_app/templates/main_app/book_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
    <h3>Do you want to delete {{object.title}}</h3>

    <form action="" method="POST">
        {% csrf_token %}
        <input type="submit" value="Delete" class="btn">
        <a href="{% url 'details' object.id %}">Cancel</a>
    </form>
{% endblock %}

main_app/templates/main_app/book_form.html
{% extends 'base.html' %}

{% block content %}

{% if object %}
    <h1>Edit <div>{{object.title}}</div></h1>
{% else %}
    <h1>Add Book</h1>
{% endif %}

<form action="" method="POST">
    {% csrf_token %}
    <table>
        {{ form.as_table}}
    </table>
    <input type="submit" value="Submit" class="btn">
</form>
{% endblock %}

main_app/templates/main_app/store_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Store</h1>

  <h4>Are you sure you want to delete {{ object.name }}?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes" class="btn">
    <a href="{% url 'store_details' object.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/store_detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Toy Details</h1>

<div class="card">
    <div>{{ toy.name }}</div>
    <div>Location: {{ toy.color }}</div>
    <div><a href="{% url 'store_update' store.id %}">Edit</a></div>
    <div><a href="{% url 'store_delete' store.id %}">Delete</a></div>    
</div>

{% endblock %}

main_app/templates/main_app/store_form.html
{% extends 'base.html' %}
{% block content %}
{% if object %}
    </h1>Edit {{object.name}} </h1>
{% else %}
    <h1>Add Store</h1>
{% endif %}
<form action="" method="post">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
</form>
{% endblock %}

main_app/templates/main_app/store_list.html
{% extends 'base.html' %}
{% block content %}
<h1>Store List</h1>

{% for store in store_list %}
<a href="{% url 'store_details' store.id %}">
    <div class="card">
        <div>{{ store.name }}</div>
        <div>{{ store.location }}</div>
    </div>
</a>
{% endfor %}
{% endblock %}